# Generated by Django 5.1 on 2024-08-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('change_own_userprofile', 'Can change own user profile')]},
        ),
    ]
