# Generated by Django 5.1 on 2024-08-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0007_alter_course_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
