# Generated by Django 5.1 on 2024-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0009_alter_course_options_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
