# Generated by Django 5.1 on 2024-09-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform', '0010_remove_section_description_contentitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.AddField(
            model_name='section',
            name='next_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_section_link', to='learning_platform.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='previous_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_section_link', to='learning_platform.section'),
        ),
    ]
